# Carga de datos a travez de la funcion read_csv

In [6]:
import pandas as pd
import os

In [7]:
relative_mainpath = '../resources/datasets'
filename = 'titanic/titanic3.csv'
fullpath = os.path.join(relative_mainpath, filename)

In [8]:
data = pd.read_csv(fullpath)

In [9]:
data.head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"

In [10]:

"""
    read_csv(
           filepath='/absolute/path/or/relative/path', 
           sep='| or : or ; or , or regex', 
           dtype={ "columA": np.float64, "columB": np.int32 },
           header=1,
           names={'ingresos', 'edad'...},
           skiprows=13,
           index_col=3,
           skip_blank_lines=True
        )
    ---------------
    dtype => Para dar un formato especifico a la columna antes de hacer cualquier operacion con ella
    header => Es para especificar cual fila es la cabecera del documento
    names => Podemos usarlo para indicar el nombre de las columnas array o lista
    skiprows => Para saltarse un numero de filas a la hora de leer el fichero
    index_col => Argumento tipo numerico para darle un etiquetado, poner alguna columna como identificador
    skip_blank_lines => Sirve para saltar campos en blanco y dejarlos en blanco, no NaN
"""
print('ok')

ok

In [11]:
data2 = pd.read_csv(relative_mainpath + '/' + 'customer-churn-model/Customer Churn Model.txt')

In [12]:
data2.head()

,State,Account Length,Area Code,Phone,Int'l Plan,VMail Plan,VMail Message,Day Mins,Day Calls,Day Charge,...,Eve Calls,Eve Charge,Night Mins,Night Calls,Night Charge,Intl Mins,Intl Calls,Intl Charge,CustServ Calls,Churn?
0,KS,128,415,382-4657,no,yes,25,265.1,110,45.07,...,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False.
1,OH,107,415,371-7191,no,yes,26,161.6,123,27.47,...,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False.
2,NJ,137,415,358-1921,no,no,0,243.4,114,41.38,...,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False.
3,OH,84,408,375-9999,yes,no,0,299.4,71,50.90,...,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False.
4,OK,75,415,330-6626,yes,no,0,166.7,113,28.34,...,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False.

In [13]:
data2.columns.values

<StringArray>
[         'State', 'Account Length',      'Area Code',          'Phone',
     'Int'l Plan',     'VMail Plan',  'VMail Message',       'Day Mins',
      'Day Calls',     'Day Charge',       'Eve Mins',      'Eve Calls',
     'Eve Charge',     'Night Mins',    'Night Calls',   'Night Charge',
      'Intl Mins',     'Intl Calls',    'Intl Charge', 'CustServ Calls',
         'Churn?']
Length: 21, dtype: str

In [14]:
data_cols = pd.read_csv(relative_mainpath + '/' + 'customer-churn-model/Customer Churn Columns.csv')
data_col_list = data_cols['Column_Names'].tolist()
data2 = pd.read_csv(relative_mainpath + '/' + 'customer-churn-model/Customer Churn Model.txt', header=None, names=data_col_list)
# Personalizando cabecera de mi data frame
data2

,A,B,C,D,E,F,G,H,I,J,...,L,M,N,O,P,Q,R,S,T,U
0,State,Account Length,Area Code,Phone,Int'l Plan,VMail Plan,VMail Message,Day Mins,Day Calls,Day Charge,...,Eve Calls,Eve Charge,Night Mins,Night Calls,Night Charge,Intl Mins,Intl Calls,Intl Charge,CustServ Calls,Churn?
1,KS,128,415,382-4657,no,yes,25,265.100000,110,45.070000,...,99,16.780000,244.700000,91,11.010000,10.000000,3,2.700000,1,False.
2,OH,107,415,371-7191,no,yes,26,161.600000,123,27.470000,...,103,16.620000,254.400000,103,11.450000,13.700000,3,3.700000,1,False.
3,NJ,137,415,358-1921,no,no,0,243.400000,114,41.380000,...,110,10.300000,162.600000,104,7.320000,12.200000,5,3.290000,0,False.
4,OH,84,408,375-9999,yes,no,0,299.400000,71,50.900000,...,88,5.260000,196.900000,89,8.860000,6.600000,7,1.780000,2,False.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3329,AZ,192,415,414-4276,no,yes,36,156.200000,77,26.550000,...,126,18.320000,279.100000,83,12.560000,9.900000,6,2.670000,2,False.
3330,WV,68,415,370-3271,no,no,0,231.100000,57,39.290000,...,55,13.040000,191.300000,123,8.610000,9.600000,4,2.590000,3,False.
3331,RI,28,510,328-8230,no,no,0,180.800000,109,30.740000,...,58,24.550000,191.900000,91,8.640000,14.100000,6,3.810000,2,False.
3332,CT,184,510,364-6381,yes,no,0,213.800000,105,36.350000,...,84,13.570000,139.200000,137,6.260000,5.000000,10,1.350000,2,False.
3333,TN,74,415,400-4344,no,yes,25,234.400000,113,39.850000,...,82,22.600000,241.400000,77,10.860000,13.700000,4,3.700000,0,False.

# Carga de datos a travez de la funcion open

Nota: Para hacer carga de archivos muy grandes, pandas no es la libreria ideal ya que esta libreria hacer una carga de golpe de todo el archivo, por el contrario, la funcion open permite leer el contenido linea a linea para segmentarlo en bloques o segun como se requiera.

In [15]:
filename_churn = 'customer-churn-model/Customer Churn Model.txt'

In [16]:
url_file = os.path.join(relative_mainpath, filename_churn)
data3 = open(url_file, 'r')

In [17]:
"""
    readline() => Lee linea a linea
    strip() => Se usa para remover los espacios en blanco tanto al principio como al final de la linea
    split() => Divide en pequenios fragmentos por un delimitador
"""
cols = data3.readline().strip().split(',')

In [18]:
n_cols = len(cols)

In [19]:
counter = 0
main_dict = {}
for col in cols:
    main_dict[col] = []
main_dict

{'State': [],
 'Account Length': [],
 'Area Code': [],
 'Phone': [],
 "Int'l Plan": [],
 'VMail Plan': [],
 'VMail Message': [],
 'Day Mins': [],
 'Day Calls': [],
 'Day Charge': [],
 'Eve Mins': [],
 'Eve Calls': [],
 'Eve Charge': [],
 'Night Mins': [],
 'Night Calls': [],
 'Night Charge': [],
 'Intl Mins': [],
 'Intl Calls': [],
 'Intl Charge': [],
 'CustServ Calls': [],
 'Churn?': []}

In [20]:
for line in data3:
    values = line.strip().split(',')
    for i in range(len(cols)):
        main_dict[cols[i]].append(values[i])
    counter += 1
print("El data set tiene %d files y %d columnas" % (counter, n_cols))

El data set tiene 3333 files y 21 columnas

In [30]:
df3 = pd.DataFrame(main_dict)
df3.head()

,State,Account Length,Area Code,Phone,Int'l Plan,VMail Plan,VMail Message,Day Mins,Day Calls,Day Charge,...,Eve Calls,Eve Charge,Night Mins,Night Calls,Night Charge,Intl Mins,Intl Calls,Intl Charge,CustServ Calls,Churn?
0,KS,128,415,382-4657,no,yes,25,265.100000,110,45.070000,...,99,16.780000,244.700000,91,11.010000,10.000000,3,2.700000,1,False.
1,OH,107,415,371-7191,no,yes,26,161.600000,123,27.470000,...,103,16.620000,254.400000,103,11.450000,13.700000,3,3.700000,1,False.
2,NJ,137,415,358-1921,no,no,0,243.400000,114,41.380000,...,110,10.300000,162.600000,104,7.320000,12.200000,5,3.290000,0,False.
3,OH,84,408,375-9999,yes,no,0,299.400000,71,50.900000,...,88,5.260000,196.900000,89,8.860000,6.600000,7,1.780000,2,False.
4,OK,75,415,330-6626,yes,no,0,166.700000,113,28.340000,...,122,12.610000,186.900000,121,8.410000,10.100000,3,2.730000,3,False.

Es importante saber que en este caso hemos usado el modo "r" de de la funcion open(), sin embargo, es justo tener cuidado para el caso en que quiera abir en modo "w" ya que eso hace que el contenido previo del archivo sea eliminado y reemplazado por el nuevo contenido. Es mejor, si queremos modificar el documento, abrirlo en modo "a" (append) para hacer la insercion de la nueva informacion, al final del archivo

## Lectura y escritura de ficheros

In [22]:
infile = url_file
outfile = os.path.join(relative_mainpath, 'customer-churn-model/Tab Customer Churn Model.txt')

In [28]:
with open(infile, 'r') as infile1:
    with open(outfile, 'w') as outfile1:
        for line in infile1:
            fields = line.strip().split(',')
            outfile1.write("\t".join(fields))
            outfile1.write('\n')

In [29]:
df4 = pd.read_csv(outfile, sep='\t')
df4

,State,Account Length,Area Code,Phone,Int'l Plan,VMail Plan,VMail Message,Day Mins,Day Calls,Day Charge,...,Eve Calls,Eve Charge,Night Mins,Night Calls,Night Charge,Intl Mins,Intl Calls,Intl Charge,CustServ Calls,Churn?
0,KS,128,415,382-4657,no,yes,25,265.1,110,45.07,...,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False.
1,OH,107,415,371-7191,no,yes,26,161.6,123,27.47,...,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False.
2,NJ,137,415,358-1921,no,no,0,243.4,114,41.38,...,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False.
3,OH,84,408,375-9999,yes,no,0,299.4,71,50.90,...,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False.
4,OK,75,415,330-6626,yes,no,0,166.7,113,28.34,...,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3328,AZ,192,415,414-4276,no,yes,36,156.2,77,26.55,...,126,18.32,279.1,83,12.56,9.9,6,2.67,2,False.
3329,WV,68,415,370-3271,no,no,0,231.1,57,39.29,...,55,13.04,191.3,123,8.61,9.6,4,2.59,3,False.
3330,RI,28,510,328-8230,no,no,0,180.8,109,30.74,...,58,24.55,191.9,91,8.64,14.1,6,3.81,2,False.
3331,CT,184,510,364-6381,yes,no,0,213.8,105,36.35,...,84,13.57,139.2,137,6.26,5.0,10,1.35,2,False.
3332,TN,74,415,400-4344,no,yes,25,234.4,113,39.85,...,82,22.60,241.4,77,10.86,13.7,4,3.70,0,False.

## Ficheros XLS y XLSX

In [39]:
titanic_path = os.path.join(relative_mainpath, 'titanic/titanic3.xlsx')

In [41]:
titanic3 = pd.read_excel(titanic_path, 'titanic3')

In [44]:
titanic3.to_csv(relative_mainpath + '/titanic/titanic_custom2.csv')

In [46]:
titanic3.to_excel(relative_mainpath + '/titanic/titanic_custom_excel.xlsx')