# Agregacion de datos por categoria

In [1]:
import numpy as np
import pandas as pd

In [2]:
gender = ['Male', 'Female']
income = ['Poor', 'Middle Class', 'Rich']

In [3]:
n = 500

gender_data = []
income_data = []

for i in range(0, n):
    gender_data.append(np.random.choice(gender))
    income_data.append(np.random.choice(income))

In [5]:
gender_data[:10]

[np.str_('Male'),
 np.str_('Female'),
 np.str_('Male'),
 np.str_('Female'),
 np.str_('Male'),
 np.str_('Female'),
 np.str_('Female'),
 np.str_('Female'),
 np.str_('Female'),
 np.str_('Female')]

In [7]:
income_data[:10]

[np.str_('Middle Class'),
 np.str_('Poor'),
 np.str_('Poor'),
 np.str_('Middle Class'),
 np.str_('Poor'),
 np.str_('Rich'),
 np.str_('Poor'),
 np.str_('Poor'),
 np.str_('Middle Class'),
 np.str_('Rich')]

In [8]:
# Z => N(0, 1)
# N(m, s) => m + s * Z

height = 160 + 30 * np.random.randn(n)
weight = 65 + 25 * np.random.randn(n)
age = 30 + 12 * np.random.randn(n)
income = 18000 + 3500 * np.random.randn(n)

In [9]:
data = pd.DataFrame(
    {
        "Gender": gender_data,
        "Economic Status": income_data,
        "Height": height,
        "Weight": weight,
        "Income": income
    }
)

In [10]:
data.head()

   Gender Economic Status      Height     Weight        Income
0    Male    Middle Class  185.411836  92.358173  18831.470919
1  Female            Poor  145.657774  69.896792  15397.211611
2    Male            Poor  165.493229  31.050109  19640.966881
3  Female    Middle Class  174.000278  62.760465  19994.327477
4    Male            Poor  147.590209  69.836246  15079.081752

## Agupacion de datos

In [12]:
grouped_gender = data.groupby("Gender")

In [13]:
grouped_gender.groups

{'Female': [1, 3, 5, 6, 7, 8, 9, 12, 17, 19, 21, 23, 24, 25, 26, 29, 30, 31, 34, 37, 38, 39, 45, 48, 49, 51, 52, 54, 55, 58, 61, 63, 65, 68, 71, 72, 73, 76, 79, 81, 82, 85, 89, 90, 92, 93, 98, 100, 101, 102, 107, 109, 115, 119, 120, 122, 125, 129, 130, 131, 132, 133, 135, 138, 139, 141, 142, 143, 147, 149, 154, 155, 156, 158, 161, 162, 164, 165, 166, 168, 170, 171, 173, 180, 183, 185, 187, 188, 191, 193, 194, 195, 196, 198, 199, 200, 201, 202, 204, 206, ...], 'Male': [0, 2, 4, 10, 11, 13, 14, 15, 16, 18, 20, 22, 27, 28, 32, 33, 35, 36, 40, 41, 42, 43, 44, 46, 47, 50, 53, 56, 57, 59, 60, 62, 64, 66, 67, 69, 70, 74, 75, 77, 78, 80, 83, 84, 86, 87, 88, 91, 94, 95, 96, 97, 99, 103, 104, 105, 106, 108, 110, 111, 112, 113, 114, 116, 117, 118, 121, 123, 124, 126, 127, 128, 134, 136, 137, 140, 144, 145, 146, 148, 150, 151, 152, 153, 157, 159, 160, 163, 167, 169, 172, 174, 175, 176, 177, 178, 179, 181, 182, 184, ...]}

In [14]:
for names, groups in grouped_gender:
    print(names)
    print(groups)

Female
     Gender Economic Status      Height      Weight        Income
1    Female            Poor  145.657774   69.896792  15397.211611
3    Female    Middle Class  174.000278   62.760465  19994.327477
5    Female            Rich  187.554716   57.402452  18654.187741
6    Female            Poor  138.808110   21.844075  14847.911412
7    Female            Poor  126.743904   99.117308  25088.857127
..      ...             ...         ...         ...           ...
488  Female            Rich  177.664231  132.645203  16757.447987
489  Female    Middle Class  168.559719   28.964664  13083.495662
491  Female            Poor  130.782081   86.197924  16194.176550
496  Female            Rich  211.782145   62.674802  19454.553992
497  Female    Middle Class  146.554457   73.787208  15755.193712

[241 rows x 5 columns]
Male
    Gender Economic Status      Height      Weight        Income
0     Male    Middle Class  185.411836   92.358173  18831.470919
2     Male            Poor  165.493229   31.050109  19640.966881
4     Male            Poor  147.590209   69.836246  15079.081752
10    Male            Poor  103.719188   58.444386  13393.208160
11    Male            Poor  116.513698   53.642698  13987.921550
..     ...             ...         ...         ...           ...
493   Male            Poor  147.799341   22.428136  14892.143735
494   Male            Poor  166.215068  107.674626  25760.789067
495   Male            Rich  177.926506   64.813341  18911.202738
498   Male            Rich  175.613249   81.165716  14620.847442
499   Male    Middle Class  158.991048   62.072811  12838.268472

[259 rows x 5 columns]

In [15]:
grouped_gender.get_group("Female")

     Gender Economic Status      Height      Weight        Income
1    Female            Poor  145.657774   69.896792  15397.211611
3    Female    Middle Class  174.000278   62.760465  19994.327477
5    Female            Rich  187.554716   57.402452  18654.187741
6    Female            Poor  138.808110   21.844075  14847.911412
7    Female            Poor  126.743904   99.117308  25088.857127
..      ...             ...         ...         ...           ...
488  Female            Rich  177.664231  132.645203  16757.447987
489  Female    Middle Class  168.559719   28.964664  13083.495662
491  Female            Poor  130.782081   86.197924  16194.176550
496  Female            Rich  211.782145   62.674802  19454.553992
497  Female    Middle Class  146.554457   73.787208  15755.193712

[241 rows x 5 columns]

In [16]:
double_group = data.groupby(['Gender', 'Economic Status'])

In [17]:
len(double_group)

6

In [18]:
for names, groups in double_group:
    print(names)
    print(groups)

(np.str_('Female'), np.str_('Middle Class'))
     Gender Economic Status      Height      Weight        Income
3    Female    Middle Class  174.000278   62.760465  19994.327477
8    Female    Middle Class  152.858110   49.479194  17669.320024
17   Female    Middle Class  174.532194   55.355273  15933.755716
23   Female    Middle Class  108.520834   39.584131  19478.875327
26   Female    Middle Class  154.486077   55.358210  17427.791314
..      ...             ...         ...         ...           ...
480  Female    Middle Class  169.306541   67.733509  18772.498606
483  Female    Middle Class  173.535540  103.025682  17150.806562
484  Female    Middle Class  206.980187   70.794555  18896.170731
489  Female    Middle Class  168.559719   28.964664  13083.495662
497  Female    Middle Class  146.554457   73.787208  15755.193712

[95 rows x 5 columns]
(np.str_('Female'), np.str_('Poor'))
     Gender Economic Status      Height      Weight        Income
1    Female            Poor  145.657774   69.896792  15397.211611
6    Female            Poor  138.808110   21.844075  14847.911412
7    Female            Poor  126.743904   99.117308  25088.857127
12   Female            Poor  191.313508   90.922833  19628.457914
25   Female            Poor  152.260643   88.769918  17048.933802
..      ...             ...         ...         ...           ...
472  Female            Poor  154.858742   65.210896  23557.051106
482  Female            Poor  128.675409   48.108174  17793.742320
486  Female            Poor  164.890915  104.513445  18215.706261
487  Female            Poor  194.110984   52.417712  18012.945282
491  Female            Poor  130.782081   86.197924  16194.176550

[73 rows x 5 columns]
(np.str_('Female'), np.str_('Rich'))
     Gender Economic Status      Height      Weight        Income
5    Female            Rich  187.554716   57.402452  18654.187741
9    Female            Rich  200.937877   62.657739  19185.074298
19   Female            Rich  131.303522   63.493225  15329.532082
21   Female            Rich  143.404378   82.270708  19323.543752
24   Female            Rich  115.952578   67.808876  17346.678613
..      ...             ...         ...         ...           ...
461  Female            Rich  169.214029   61.234964  15215.782790
471  Female            Rich  179.925280   52.000648  22796.578641
479  Female            Rich  113.735647   94.372179  14219.659514
488  Female            Rich  177.664231  132.645203  16757.447987
496  Female            Rich  211.782145   62.674802  19454.553992

[73 rows x 5 columns]
(np.str_('Male'), np.str_('Middle Class'))
    Gender Economic Status      Height      Weight        Income
0     Male    Middle Class  185.411836   92.358173  18831.470919
15    Male    Middle Class  204.703215   96.383997  10594.524029
16    Male    Middle Class  110.093645   87.579389  26130.201453
20    Male    Middle Class  150.940683   51.848249  15837.064068
27    Male    Middle Class  168.487113  117.734308  22514.070717
..     ...             ...         ...         ...           ...
470   Male    Middle Class  126.233529   42.462996  19990.439505
473   Male    Middle Class  117.516631   88.378634  21716.091102
481   Male    Middle Class   99.699600   63.783517  22454.121947
492   Male    Middle Class  196.490587   50.350628  23204.968578
499   Male    Middle Class  158.991048   62.072811  12838.268472

[77 rows x 5 columns]
(np.str_('Male'), np.str_('Poor'))
    Gender Economic Status      Height      Weight        Income
2     Male            Poor  165.493229   31.050109  19640.966881
4     Male            Poor  147.590209   69.836246  15079.081752
10    Male            Poor  103.719188   58.444386  13393.208160
11    Male            Poor  116.513698   53.642698  13987.921550
18    Male            Poor  137.448218   38.876369  21431.612423
..     ...             ...         ...         ...           ...
475   Male            Poor  168.176021   83.303023  24172.686575
485   Male            Poor  175.682096   97.982094  22047.355411
490   Male            Poor  142.976905   68.429776  19367.390921
493   Male            Poor  147.799341   22.428136  14892.143735
494   Male            Poor  166.215068  107.674626  25760.789067

[83 rows x 5 columns]
(np.str_('Male'), np.str_('Rich'))
    Gender Economic Status      Height     Weight        Income
13    Male            Rich  157.316329  56.228975  15355.010032
14    Male            Rich  108.913383  56.320565  18309.419375
22    Male            Rich  172.362553  34.357537  15633.521210
33    Male            Rich  208.031815  49.312821  15931.401174
36    Male            Rich  198.882971  71.953737  21331.981461
..     ...             ...         ...        ...           ...
469   Male            Rich  185.705468  46.156442  13657.495007
476   Male            Rich  177.922020  81.231540  12812.316344
477   Male            Rich  149.926028  63.719361  21574.342137
495   Male            Rich  177.926506  64.813341  18911.202738
498   Male            Rich  175.613249  81.165716  14620.847442

[99 rows x 5 columns]

## Operaciones sobre datos agrupados

In [19]:
double_group.sum()

                              Height       Weight        Income
Gender Economic Status
Female Middle Class     15825.882113  5921.686208  1.710795e+06
       Poor             11563.156402  4750.093084  1.292892e+06
       Rich             11960.245295  4488.257211  1.284819e+06
Male   Middle Class     12503.760896  5282.278279  1.403969e+06
       Poor             13225.057164  5371.299972  1.502166e+06
       Rich             16309.622738  6575.560423  1.736876e+06

In [20]:
double_group.mean()

                            Height     Weight        Income
Gender Economic Status
Female Middle Class     166.588233  62.333539  18008.366687
       Poor             158.399403  65.069768  17710.844343
       Rich             163.838977  61.482975  17600.254459
Male   Middle Class     162.386505  68.601017  18233.358911
       Poor             159.338038  64.714457  18098.390164
       Rich             164.743664  66.419802  17544.198300

In [21]:
double_group.size()

Gender  Economic Status
Female  Middle Class       95
        Poor               73
        Rich               73
Male    Middle Class       77
        Poor               83
        Rich               99
dtype: int64

In [22]:
double_group.describe()

                       Height                                                \
                        count        mean        std        min         25%
Gender Economic Status
Female Middle Class      95.0  166.588233  29.798399  83.514273  149.164504
       Poor              73.0  158.399403  28.061953  80.853018  138.808110
       Rich              73.0  163.838977  34.168376  62.107275  143.344869
Male   Middle Class      77.0  162.386505  33.289402  96.976030  138.444503
       Poor              83.0  159.338038  27.410532  92.737479  142.122923
       Rich              99.0  164.743664  31.123675  86.075451  144.167176

                                                           Weight             \
                               50%         75%         max  count       mean
Gender Economic Status
Female Middle Class     166.772196  184.781331  233.593045   95.0  62.333539
       Poor             157.438069  181.917297  226.477681   73.0  65.069768
       Rich             164.257139  185.170152  238.876776   73.0  61.482975
Male   Middle Class     162.530912  185.411836  246.891786   77.0  68.601017
       Poor             159.372112  176.691692  235.004395   83.0  64.714457
       Rich             166.297432  187.036699  240.886822   99.0  66.419802

                        ...                        Income                \
                        ...        75%         max  count          mean
Gender Economic Status  ...
Female Middle Class     ...  76.967237  124.091476   95.0  18008.366687
       Poor             ...  80.563350  131.751619   73.0  17710.844343
       Rich             ...  80.951021  132.645203   73.0  17600.254459
Male   Middle Class     ...  83.141265  119.290306   77.0  18233.358911
       Poor             ...  81.915904  118.027687   83.0  18098.390164
       Rich             ...  86.607160  134.554963   99.0  17544.198300

                                                                               \
                                std           min           25%           50%
Gender Economic Status
Female Middle Class     3932.348631   8744.932178  15445.942294  17669.320024
       Poor             3621.423513   9530.339697  15196.161679  17437.191962
       Rich             3744.601845   9143.513715  15214.716819  17808.932657
Male   Middle Class     4011.330194  10329.108698  14749.601255  18789.389235
       Poor             3751.818204   9281.574491  15254.848816  18134.959134
       Rich             3496.018352   9598.453090  15108.002669  17684.011534


                                 75%           max
Gender Economic Status
Female Middle Class     20512.537718  29588.853834
       Poor             20330.758328  25088.857127
       Rich             19454.553992  25700.572630
Male   Middle Class     21437.048148  26130.201453
       Poor             20797.543159  25760.789067
       Rich             20369.605779  25730.220138

[6 rows x 24 columns]

In [23]:
grouped_income = double_group['Income']

In [24]:
grouped_income.describe()

                        count          mean          std           min  \
Gender Economic Status
Female Middle Class      95.0  18008.366687  3932.348631   8744.932178
       Poor              73.0  17710.844343  3621.423513   9530.339697
       Rich              73.0  17600.254459  3744.601845   9143.513715
Male   Middle Class      77.0  18233.358911  4011.330194  10329.108698
       Poor              83.0  18098.390164  3751.818204   9281.574491
       Rich              99.0  17544.198300  3496.018352   9598.453090

                                 25%           50%           75%           max
Gender Economic Status
Female Middle Class     15445.942294  17669.320024  20512.537718  29588.853834
       Poor             15196.161679  17437.191962  20330.758328  25088.857127
       Rich             15214.716819  17808.932657  19454.553992  25700.572630
Male   Middle Class     14749.601255  18789.389235  21437.048148  26130.201453
       Poor             15254.848816  18134.959134  20797.543159  25760.789067
       Rich             15108.002669  17684.011534  20369.605779  25730.220138

In [26]:
double_group.aggregate(
    {
        'Income': np.sum,
        'Height': np.std
    }
)

                              Income     Height
Gender Economic Status
Female Middle Class     1.710795e+06  29.641151
       Poor             1.292892e+06  27.869085
       Rich             1.284819e+06  33.933539
Male   Middle Class     1.403969e+06  33.072531
       Poor             1.502166e+06  27.244908
       Rich             1.736876e+06  30.966085

In [27]:
double_group.aggregate(
    {
        'Height': lambda h:(np.mean(h))/np.std(h)
    }
)

                          Height
Gender Economic Status
Female Middle Class     5.620168
       Poor             5.683696
       Rich             4.828231
Male   Middle Class     4.910011
       Poor             5.848360
       Rich             5.320132

In [28]:
double_group.aggregate([np.sum, np.mean, np.std])

                              Height                              Weight  \
                                 sum        mean        std          sum
Gender Economic Status
Female Middle Class     15825.882113  166.588233  29.641151  5921.686208
       Poor             11563.156402  158.399403  27.869085  4750.093084
       Rich             11960.245295  163.838977  33.933539  4488.257211
Male   Middle Class     12503.760896  162.386505  33.072531  5282.278279
       Poor             13225.057164  159.338038  27.244908  5371.299972
       Rich             16309.622738  164.743664  30.966085  6575.560423

                                                    Income                \
                             mean        std           sum          mean
Gender Economic Status
Female Middle Class     62.333539  25.083221  1.710795e+06  18008.366687
       Poor             65.069768  24.383959  1.292892e+06  17710.844343
       Rich             61.482975  26.773519  1.284819e+06  17600.254459
Male   Middle Class     68.601017  24.572744  1.403969e+06  18233.358911
       Poor             64.714457  25.421975  1.502166e+06  18098.390164
       Rich             66.419802  27.656829  1.736876e+06  17544.198300


                                std
Gender Economic Status
Female Middle Class     3911.597307
       Poor             3596.533709
       Rich             3718.865445
Male   Middle Class     3985.197471
       Poor             3729.148400
       Rich             3478.316879

In [29]:
double_group.aggregate([lambda x: np.mean(x) / np.std(x)])

                          Height    Weight    Income
                        <lambda>  <lambda>  <lambda>
Gender Economic Status
Female Middle Class     5.620168  2.485069  4.603840
       Poor             5.683696  2.668548  4.924421
       Rich             4.828231  2.296410  4.732695
Male   Middle Class     4.910011  2.791752  4.575271
       Poor             5.848360  2.545611  4.853223
       Rich             5.320132  2.401570  5.043876